### ISSUE TITLE
Doesn't work in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by ntsarb** [poliva/lightum#57]
It doesn't work on Ubuntu 18.04 LTS. When I compile, I get the following error:

cc `pkg-config --cflags dbus-1 --cflags glib-2.0 --cflags gio-2.0 --cflags libsystemd-login` -Wall -Wextra -Wwrite-strings -g -O2   -c -o functions.o functions.c
Package libsystemd-login was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsystemd-login.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsystemd-login' found
In file included from functions.c:23:0:
lightum.h:2:10: fatal error: gio/gio.h: No such file or directory
 #include <gio/gio.h>
          ^~~~~~~~~~~
compilation terminated.
<builtin>: recipe for target 'functions.o' failed
make: *** [functions.o] Error 1
